package DataDictionaryDsl.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Field_Constraints extends BaseConstraintsDescriptor {
  public Field_Constraints() {
    super(CONCEPTS.Field$9$);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Field$9$ = MetaAdapterFactory.getConcept(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9c14433L, "DataDictionaryDsl.structure.Field");
  }
}
