package DataDictionaryDsl.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Aggregation = 0;
  public static final int DataDictionary = 1;
  public static final int Exclusive = 2;
  public static final int Field = 3;
  public static final int IAbstractElement = 4;
  public static final int IAbstractStructure = 5;
  public static final int ISpecialization = 6;
  public static final int NonExclusive = 7;
  public static final int Set = 8;
  public static final int StructureDefinition = 9;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x16d63821a9174aafL, 0xa85f305cd4a0013fL);
    builder.put(0x73ede05be9c14454L, Aggregation);
    builder.put(0x73ede05be9bfff49L, DataDictionary);
    builder.put(0x7171b68977873f0L, Exclusive);
    builder.put(0x73ede05be9c14433L, Field);
    builder.put(0x7171b68977873e6L, IAbstractElement);
    builder.put(0x7171b68977873e5L, IAbstractStructure);
    builder.put(0x7171b68977873efL, ISpecialization);
    builder.put(0x73ede05be9c1bfe4L, NonExclusive);
    builder.put(0x73ede05be9c14455L, Set);
    builder.put(0x73ede05be9bfff46L, StructureDefinition);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
