package DataDictionaryDsl.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAggregation = createDescriptorForAggregation();
  /*package*/ final ConceptDescriptor myConceptDataDictionary = createDescriptorForDataDictionary();
  /*package*/ final ConceptDescriptor myConceptExclusive = createDescriptorForExclusive();
  /*package*/ final ConceptDescriptor myConceptField = createDescriptorForField();
  /*package*/ final ConceptDescriptor myConceptIAbstractElement = createDescriptorForIAbstractElement();
  /*package*/ final ConceptDescriptor myConceptIAbstractStructure = createDescriptorForIAbstractStructure();
  /*package*/ final ConceptDescriptor myConceptISpecialization = createDescriptorForISpecialization();
  /*package*/ final ConceptDescriptor myConceptNonExclusive = createDescriptorForNonExclusive();
  /*package*/ final ConceptDescriptor myConceptSet = createDescriptorForSet();
  /*package*/ final ConceptDescriptor myConceptStructureDefinition = createDescriptorForStructureDefinition();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAggregation, myConceptDataDictionary, myConceptExclusive, myConceptField, myConceptIAbstractElement, myConceptIAbstractStructure, myConceptISpecialization, myConceptNonExclusive, myConceptSet, myConceptStructureDefinition);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Aggregation:
        return myConceptAggregation;
      case LanguageConceptSwitch.DataDictionary:
        return myConceptDataDictionary;
      case LanguageConceptSwitch.Exclusive:
        return myConceptExclusive;
      case LanguageConceptSwitch.Field:
        return myConceptField;
      case LanguageConceptSwitch.IAbstractElement:
        return myConceptIAbstractElement;
      case LanguageConceptSwitch.IAbstractStructure:
        return myConceptIAbstractStructure;
      case LanguageConceptSwitch.ISpecialization:
        return myConceptISpecialization;
      case LanguageConceptSwitch.NonExclusive:
        return myConceptNonExclusive;
      case LanguageConceptSwitch.Set:
        return myConceptSet;
      case LanguageConceptSwitch.StructureDefinition:
        return myConceptStructureDefinition;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList();
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAggregation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "Aggregation", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9c14454L);
    b.class_(false, false, false);
    b.parent(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e5L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/8353579569210541140");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataDictionary() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "DataDictionary", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9bfff49L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/8353579569210457929");
    b.version(2);
    b.aggregate("structures", 0x73ede05be9bfff4cL).target(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9bfff46L).optional(true).ordered(true).multiple(true).origin("8353579569210457932").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForExclusive() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "Exclusive", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873f0L);
    b.class_(false, false, false);
    b.parent(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873efL);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/510907218761642992");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "Field", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9c14433L);
    b.class_(false, false, false);
    b.parent(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e6L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/8353579569210541107");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIAbstractElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "IAbstractElement", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e6L);
    b.interface_();
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/510907218761642982");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIAbstractStructure() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "IAbstractStructure", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e5L);
    b.interface_();
    b.parent(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e6L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/510907218761642981");
    b.version(2);
    b.aggregate("elements", 0x7171b68977873e9L).target(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e6L).optional(true).ordered(true).multiple(true).origin("510907218761642985").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForISpecialization() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "ISpecialization", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873efL);
    b.interface_();
    b.parent(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e5L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/510907218761642991");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNonExclusive() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "NonExclusive", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9c1bfe4L);
    b.class_(false, false, false);
    b.parent(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873efL);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/8353579569210572772");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "Set", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9c14455L);
    b.class_(false, false, false);
    b.parent(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e5L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/8353579569210541141");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStructureDefinition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DataDictionaryDsl", "StructureDefinition", 0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x73ede05be9bfff46L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:bb0e4ed0-51eb-4179-aa62-896788d45e4f(DataDictionaryDsl.structure)/8353579569210457926");
    b.version(2);
    b.aggregate("structure", 0x73ede05be9c17ae9L).target(0x16d63821a9174aafL, 0xa85f305cd4a0013fL, 0x7171b68977873e5L).optional(false).ordered(true).multiple(false).origin("8353579569210555113").done();
    return b.create();
  }
}
